M48
; DRILL file {KiCad (6.0.6-0)} date 2022 October 02, Sunday 15:03:49
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-02T15:03:49+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0276
%
G90
G05
T1
X5.6822Y-5.4015
X5.9098Y-5.4015
X6.2005Y-5.4912
X6.2675Y-5.4912
T0
M30
