M48
; DRILL file {KiCad (6.0.6-0)} date 2022 August 02, Tuesday 12:10:40
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-02T12:10:40+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0276
%
G90
G05
T1
X5.4882Y-5.4395
X5.4885Y-2.4638
X5.5555Y-2.4638
X5.7158Y-5.4395
T0
M30
